"""neuro-analyzer — quantitative pediatric MRI re-analysis pipeline.

ESTA HERRAMIENTA ES PARA INVESTIGACIÓN Y EDUCACIÓN ÚNICAMENTE.
NO ESTÁ APROBADA POR COFEPRIS, FDA, EMA NI NINGUNA AUTORIDAD SANITARIA.
NO DEBE UTILIZARSE PARA DIAGNÓSTICO, TRATAMIENTO O TOMA DE DECISIONES CLÍNICAS.

THIS TOOL IS FOR RESEARCH AND EDUCATIONAL PURPOSES ONLY.
NOT APPROVED BY ANY REGULATORY AUTHORITY (FDA, EMA, COFEPRIS, ETC.).
NOT INTENDED FOR CLINICAL DIAGNOSIS OR TREATMENT DECISIONS.
"""

__version__ = "0.1.0"
